#!/bin/bash
#SBATCH --job-name={JOBNAME}
#SBATCH --nodes={SELECT}
#SBATCH --partition={QUEUE}
#SBATCH --tasks-per-node={NCPUS}
#SBATCH --ntasks={MPIPROCS}
#SBATCH --time={WALL}
#sbatch --mem-per-cpu=64000M
#SBATCH --output={JOBNAME}.log
#SBATCH --exclusive

cd $SLURM_SUBMIT_DIR
echo $SLURM_SUBMIT_DIR

source ./env_{comp_env}.sh

echo "============================="

cd {DIRBASE}
export TMPDIR={DIRBASE}/tmp

ulimit -s unlimited

#IMPI
MPI_PARAMS="-iface ib0 -bind-to core -map-by core"

export OMP_NUM_THREADS=1
mpirun {EXECUTABLE} &> {JOBNAME}.out

exit
