#!/bin/bash
#SBATCH --job-name={JOBNAME}
#SBATCH --nodes={SELECT}
#SBATCH --partition={QUEUE}
#SBATCH --tasks-per-node={NCPUS}
#SBATCH --ntasks={MPIPROCS}
#SBATCH --time={WALL}
#sbatch --mem-per-cpu=64000M
#SBATCH --output={JOBNAME}.log
#SBATCH --exclusive

cd $SLURM_SUBMIT_DIR
echo $SLURM_SUBMIT_DIR
module swap gnu9 intel
module swap openmpi4 impi
module load phdf5
module load netcdf
module load netcdf-fortran
module load hwloc
echo "Lista de módulos carregados: "
module list
echo "============================="

cd {DIRBASE}
export TMPDIR={DIRBASE}/tmp

ulimit -s unlimited
MPI_PARAMS="-iface ib0 -bind-to core -map-by core"
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export I_MPI_DEBUG=5
export MKL_DEBUG_CPU_TYPE=5
mpirun -env MKL_DEBUG_CPU_TYPE=5 -env UCX_NET_DEVICES=mlx5_0:1 -genvall {EXECUTABLE} &> {JOBNAME}.out
